# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Getture

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Simple Jekyll theme to host internal/external events happening in and around your area. Free free to contribute or fork the repo.

# Webapp coordinates
url: "http://localhost:4000"
baseurl: "/assets"

#These settings might be able to go?
author: Getture Inc.
#twitter_username: 
#github_username:  boyney123/evento
company_name: Getture Inc.

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

